import type { Metadata } from "next";
import "@styles/tailwind.css";
import { ThemeProvider } from "@providers/theme-provider";
import NextAuthProvider from "@/components/providers/session-provider";
import SplashWrapper from "@/components/layouts/splash/splash-wrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body className="">
          <NextAuthProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange
            >
              <SplashWrapper>{children}</SplashWrapper>
            </ThemeProvider>
          </NextAuthProvider>
        </body>
      </html>
    </>
  );
}
